export const REGISTERED_USER = "REGISTERED_USER";
export const LOGEDIN_USER = "LOGEDIN_USER";
export const ADD_BLOG_POST = "ADD_BLOG_POST";
export const GET_BLOG_POSTS = "GET_BLOG_POSTS";
export const LOGGEDOUT_USER = "LOGGEDOUT_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const EDIT_BLOG_POST = "EDIT_BLOG_POST";
